-- ==============================================================================
-- Supabase Setup Script for Simple User Form
-- ==============================================================================
-- Run this script in the Supabase SQL Editor:
-- Dashboard -> Your Project -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- 1. Create the users table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow reading users (SELECT)
CREATE POLICY "Allow read access to users"
  ON public.users
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 4. Policy: Allow inserting new users (INSERT)
CREATE POLICY "Allow insert access to users"
  ON public.users
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);
